@echo off
echo Adding changes...
git add .
echo Committing changes...
git commit -m "Enhance: Improved navigation logic, added Print PO option, and fixed deletion reliability"
echo Pushing to main...
git push origin main
echo Done.
