@echo off
echo Stashing changes...
git stash
echo Pulling latest code from main...
git pull origin main
echo Restoration of local changes...
git stash pop
echo Backend setup...
cd backend
call npm install
call npx prisma generate
echo Frontend setup...
cd ../frontend
call npm install
echo Done.
